### View all journals in json
GET https://localhost:7176/api/ScienceJournals HTTP/1.1
Accept: application/json


### View Specific journal by id 
GET https://localhost:7176/api/ScienceJournals/1 HTTP/1.1
Accept: application/json


### Create new journal (Try future year to check for validation!)
POST https://localhost:7176/api/ScienceJournals HTTP/1.1
Accept: application/json
Content-Type: application/json
Cookie: .AspNetCore.Identity.Application=CfDJ8IyEH_NxhK1FmLPBzcQPeCCfOwx7EwI79h0NHzR7PeE94dK5J8bVmnuT1AI8o_csRBNx6MX-p7t5LTv7yXYQGIaEMPr8Mim8dZPGR-0RpHgIVVME1aAc1BxmUyhepUPuw5XjRvZRRNra-fEZDtqvOVfSEPdA-LVxYIIWAk__XmVGsDEgdkZqMHYuNL1vwIawNF0AG45ONC-ox66mAQHrtphCNggDpZ1BtT9F0aaWwht9Nj9n2w891T6DfT6zDLpwnkWfgEtTU4zPvFiLOcydGmeQFBorNjZASSvzbWi8eaKiOoJ-lBX3Iu4KQtyGQOywb-_PdgKuBaeqNcboRTUR3xdAIP_O95OV0ro0nQ8rpqw-Eoat1d3ahaRpHGCod3jKX6-VxDQQ5XRXArSFI6qFzNjA5AMyW9LVqCeWE_NfNzZ4SH7SmOPH1TyHjFJgg8qxtxapIDtgWxhSi_UbF7mnZNKb81N458oFCjD5ecKSBTVXgCYjmrBcrRJZ3Xkg0jljDNHjEIdGuReCDS7qHrqfqKIxxUpUpnQ4Qy1nU9dh-Ck29rKKEVx_WUlwHVTxRExWGABxxdrtPXU7c3dHykYUW94wO-24YW2GieLXX-Tg5ZGIdctv4gcnudOP1CQHRJQFD4NvwwRJhRmkbithQ3EhfFrEq2IfH6n2xknZ0NaxMsEnVYNhAzfkUXzW84XS0Ouz8-E8zb8DQbxlGDlTOpxafTDQhOJYptpwYgmi8MCAOMIlD6_nLmOJ2g4kBtCf8Flp05XGyCSy8lnz53BNK6cxxz3L9TGgMdUNdp3EUKA73MtyARdVpRyePycZb_jAfCg_w2KHmyHLZX-p7mhX-wto3vo

{"name":"Bio+", "price":null, "yearFounded": 2012, "countryOfOrigin": 4}


### View articles by scientist
GET https://localhost:7176/api/ScientificArticles/by-scientist/3 HTTP/1.1
Accept: application/json


### View all articles
GET https://localhost:7176/api/ScientificArticles HTTP/1.1
Accept: application/json


### Create new Article-Scientist Link
POST https://localhost:7176/api/ArticleScientistLinks HTTP/1.1
Accept: application/json
Content-Type: application/json

{"articleId":4, "scientistId":3, "isLeadResearcher": true}


### View articles NOT by scientist
GET https://localhost:7176/api/ScientificArticles/not-by-scientist/2 HTTP/1.1
Accept: application/json